import * as S from './styles'

export const GRAPH_OPTIONS = {
    clickToUse: true,
    nodes: {
      borderWidth: 0,
      color: S.BACKGROUND_COLOR,
      mass: 0.3,
      font: {
        size: 22,
      },
    },
    edges: {
      color: S.GREY,
      font: {
        size: 18,
        color: S.WHITISH,
        strokeWidth: 0,
      },
      smooth: true,
      width: 1,
      arrows: {
        to: {
          enabled: true,
          scaleFactor: 0.6
        }
      }
    },
  };

export const GRAPH_DATA = {
    graph: {
        nodes: [
            { id: 'graphscript', label: 'graphscript', ...S.SCRIPT_NODE },
            { id: 'assign_z', label: '=', ...S.ASSIGNMENT_NODE },
            { id: 'list', label: 'list', ...S.COLLECTION_NODE },
            { id: 'assign_xyz', label: '=', ...S.ASSIGNMENT_NODE },
            { id: 'formula', label: 'x + y + z', ...S.FORMULA_NODE },
            { id: 'assign_s', label: '=', ...S.ASSIGNMENT_NODE },
            { id: 'show1', label: 'show', ...S.COMMAND_NODE },
            { id: 'sum', label: 'sum', ...S.COMMAND_NODE },
            { id: 'show2', label: 'show', ...S.COMMAND_NODE },
            { id: 'if', label: 'if', ...S.FLOW_NODE },
            { id: 'less', label: 'less', ...S.CASE_NODE },
            { id: 'more', label: 'more', ...S.CASE_NODE },
            { id: 'show3', label: 'show', ...S.COMMAND_NODE },
            { id: 'struct', label: 'struct', ...S.COLLECTION_NODE },
            { id: 'when', label: 'when', ...S.FLOW_NODE },
            { id: 'x1', label: 'x', ...S.TERM_NODE },
            { id: 'y1', label: 'y', ...S.TERM_NODE },
            { id: 'z1', label: 'z', ...S.TERM_NODE },
            { id: 'x2', label: 'x', ...S.TERM_NODE },
            { id: 'y2', label: 'y', ...S.TERM_NODE },
            { id: 'z2', label: 'z', ...S.TERM_NODE },
            { id: 'x3', label: 'x', ...S.TERM_NODE },
            { id: 'y3', label: 'y', ...S.TERM_NODE },
            { id: 'z3', label: 'z', ...S.TERM_NODE },
            { id: 'x4', label: 'x', ...S.TERM_NODE },
            { id: 'y4', label: 'y', ...S.TERM_NODE },
            { id: 'x5', label: 'x', ...S.TERM_NODE },
            { id: 'y5', label: 'y', ...S.TERM_NODE },
            { id: 'z5', label: 'z', ...S.TERM_NODE },
            { id: 's1', label: 's', ...S.TERM_NODE },
            { id: 's2', label: 's', ...S.TERM_NODE },
            { id: 's3', label: 's', ...S.TERM_NODE },
            { id: 'xyz1', label: 'xyz', ...S.TERM_NODE },
            { id: 'xyz2', label: 'xyz', ...S.TERM_NODE },
            { id: 'xyz3', label: 'xyz', ...S.TERM_NODE },
            { id: 'it1', label: 'it', ...S.TERM_NODE },
            { id: 'it2', label: 'it', ...S.TERM_NODE },
            { id: 'it3', label: 'it', ...S.TERM_NODE },
            { id: 'it4', label: 'it', ...S.TERM_NODE },
            { id: 'it5', label: 'it', ...S.TERM_NODE },
            { id: 'it6', label: 'it', ...S.TERM_NODE },
            { id: 'it7', label: 'it', ...S.TERM_NODE },
            { id: 'it8', label: 'it', ...S.TERM_NODE },
            { id: 1, label: '1', ...S.VALUE_NODE },
            { id: 2, label: '2', ...S.VALUE_NODE },
            { id: 3, label: '3', ...S.VALUE_NODE },

        ],
        edges: [
            { from: 'graphscript', to: 'x1', ...S.ARG_EDGE },
            { from: 'graphscript', to: 'y1', label: 'of', ...S.ARG_EDGE },
            { from: 'graphscript', to: 'assign_z', ...S.THEN_EDGE },
            { from: 1, to: 'assign_z', ...S.GET_EDGE },
            { from: 'assign_z', to: 'z1', ...S.SET_EDGE },
            { from: 'assign_z', to: 'list', ...S.THEN_EDGE },
            { from: 'x2', to: 'list', ...S.GET_EDGE },
            { from: 'y2', to: 'list', ...S.GET_EDGE },
            { from: 'z2', to: 'list', ...S.GET_EDGE },
            { from: 'list', to: 'it7', ...S.SET_EDGE },
            { from: 'list', to: 'assign_xyz', ...S.THEN_EDGE },
            { from: 'it8', to: 'assign_xyz', ...S.GET_EDGE },
            { from: 'assign_xyz', to: 'xyz1', ...S.SET_EDGE },
            { from: 'assign_xyz', to: 'formula', ...S.THEN_EDGE },
            { from: 'x3', to: 'formula', ...S.GET_EDGE },
            { from: 'y3', to: 'formula', ...S.GET_EDGE },
            { from: 'z3', to: 'formula', ...S.GET_EDGE },
            { from: 'formula', to: 'it1', ...S.SET_EDGE },
            { from: 'it2', to: 'assign_s', ...S.GET_EDGE },
            { from: 'formula', to: 'assign_s', ...S.THEN_EDGE },
            { from: 'assign_s', to: 's1', ...S.SET_EDGE },
            { from: 'assign_s', to: 'show1', ...S.BREAK_EDGE },
            { from: 's2', to: 'show1', ...S.GET_EDGE },
            { from: 'show1', to: 'sum', ...S.THEN_EDGE },
            { from: 'xyz2', to: 'sum', ...S.GET_EDGE },
            { from: 'sum', to: 'show2', ...S.THEN_EDGE },
            { from: 'sum', to: 'it3', ...S.SET_EDGE },
            { from: 'it4', to: 'show2', ...S.GET_EDGE },
            { from: 'show2', to: 'if', ...S.BREAK_EDGE },
            { from: 'if', to: 'less', ...S.THEN_EDGE },
            { from: 'x4', to: 'less', ...S.GET_EDGE },
            { from: 2, to: 'less', ...S.GET_EDGE },
            { from: 'less', to: 'more', ...S.YES_EDGE },
            { from: 'y4', to: 'more', ...S.GET_EDGE },
            { from: 3, to: 'more', ...S.GET_EDGE },
            { from: 'more', to: 'struct', ...S.YES_EDGE },
            { from: 'show', to: 'if', ...S.THEN_EDGE },
            { from: 'if', to: 'when', ...S.THEN_EDGE },
            { from: 'struct', to: 'show3', ...S.THEN_EDGE },
            { from: 'struct', to: 'it5', ...S.SET_EDGE },
            { from: 'it6', to: 'show3', ...S.GET_EDGE },
            { from: 'x5', to: 'struct', ...S.GET_EDGE },
            { from: 'y5', to: 'struct', ...S.GET_EDGE },
            { from: 'z5', to: 'struct', ...S.GET_EDGE },
            { from: 's3', to: 'struct', ...S.GET_EDGE },
            { from: 'xyz3', to: 'struct', ...S.GET_EDGE },
            { from: 'show3', to: 'if', ...S.BREAK_EDGE },
        ]
    }
}