name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Build WASM
      run: cargo build --target wasm32-unknown-unknown --release
